#!/bin/bash

# curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/FilipAndersson245/.cfg/master/setup_fish | sh

sudo apt-add-repository ppa:fish-shell/release-3
sudo add-apt-repository ppa:maveonair/helix-editor

sudo apt update -y
sudo apt upgrade -y

sudo apt install build-essential libssl-dev zlib1g-dev libasound2-dev cmake python3-pylsp  \
libbz2-dev libreadline-dev libsqlite3-dev curl fzf ffmpeg expat pkg-config nodejs gh \
libxcb-composite0-dev libharfbuzz-dev libexpat1-dev libfreetype6-dev libblas-dev liblapack-dev \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev fish fzf helix -y

echo /usr/local/bin/fish | sudo tee -a /etc/shells
fish -c 'chsh -s (command -s fish)'

fish -c "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
fish -c "fisher install nickeb96/puffer-fish kidonng/zoxide.fish gazorby/fish-abbreviation-tips PatrickF1/fzf.fish joseluisq/gitnow@2.11.0 edc/bass"

fish -c 'set -U fish_greeting ""'
mkdir -p ~/.config/fish/completions

# Setup Pyenv.
curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/FilipAndersson245/.cfg/master/setup_pyenv | bash

# Setup and build cargo programs.
curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/FilipAndersson245/.cfg/master/setup_cargo | bash


# Only run these if in wsl
if [ -f "/proc/sys/fs/binfmt_misc/WSLInterop" ]; then
   curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/FilipAndersson245/.cfg/master/setup_wsl | bash
fi
