#!/bin/bash

curl https://pyenv.run | bash

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(pyenv init -)"' >> ~/.bashrc

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(pyenv init -)"' >> ~/.zshrc

echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(pyenv init -)"' >> ~/.bash_profile

if  type "fish" &> /dev/null; then
  if [ ! -d ~/.config ]; then
    mkdir -p ~/.config;
  fi

  fish -c 'set -Ux PYENV_ROOT $HOME/.pyenv'
  fish -c 'fish_add_path $PYENV_ROOT/bin'
  
  echo 'pyenv init - | source' > ~/.config/fish/config.fish
fi

source ~/.bashrc

fish -c 'pyenv install 3.11 3.10'
fish -c 'pyenv global 3.11'
