#!/bin/bash
sudo apt update -y
sudo apt upgrade -y

sudo apt install zsh -y

export RUNZSH="no"
export KEEP_ZSHRC="yes"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

> ~/.zshrc

echo 'export ZSH="$HOME/.oh-my-zsh"' >> ~/.zshrc
echo 'DISABLE_UNTRACKED_FILES_DIRTY="true"' >> ~/.zshrc

echo 'Install autosuggesstions'
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

echo 'Install highlighting'
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git \
  ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting

echo 'plugins=(git sudo zsh-autosuggestions fast-syntax-highlighting)' >> ~/.zshrc
echo 'source $ZSH/oh-my-zsh.sh' >> ~/.zshrc

