# Colors
# fg
# charcoal          #36454f
# WhiteSmoke        white_smoke
# Ebony Clay        #262b44
# Light slate gray  #4e6472

# bg
# Yellow Orange #FEAE34
# Candy Corn    #FEE761
# Torch Red     #FF0044
# Cerulean      #0095E9

palette = 'pill'

format = """$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

#format = """$character"""

# move the rest of the prompt to the right
right_format = """$nodejs\
$python\
$conda\
$rust\
$package\
$time\
"""

# Disable the blank line at the start of the prompt
add_newline = false
scan_timeout = 10

# Define custom colors
[palettes.pill]
# BG
yellow_orange = "#FEAE34"
candy_corn = "#FEE761"
torch_red = "#FF0044"
cerulean = "#0095E9"
bright_green = "#219245"
bright_pink = "#9A5DCC"
sea_blue = "#33658A"

# FG
charcoal =  "#36454f"
white_smoke = "#f5f5f5"



[directory]
style = "fg:yellow_orange"
format = """
[]($style)\
[ $path](inverted $style bg:black)\
[]($style)\
"""
truncation_length = 3
use_os_path_sep = false
fish_style_pwd_dir_length = 3

[git_branch]
symbol = ""
style = "fg:black bg:candy_corn"
format = """
[]($style)\
[ $symbol $branch]($style)\
"""

[git_status]
style = "fg:black bg:candy_corn"
format = """
[\\[($all_status$ahead_behind)\\]]($style)\
[ ](fg:candy_corn bg:none)\
"""
[cmd_duration]
style = "white_smoke"
format = """
[$duration]($style)\
"""

# Projects -------------------------------------------------------------
[nodejs]
symbol = "Node"
version_format = "v$major.$minor"
style = "fg:white_smoke bg:bright_green"
format = """
[](fg:bright_green)\
[$symbol $version]($style)\
[ ](fg:bright_green)\
"""

[rust]
symbol = "Rust"
version_format = "v$major.$minor"
style = "fg:white_smoke bg:bright_green"
format = """
[](fg:bright_green)\
[$symbol $version]($style)\
[ ](fg:bright_green)\
"""

[python]
symbol = "Py"
style = "fg:white_smoke bg:bright_green"
version_format = "v$major.$minor"
format = """
[](fg:bright_green)\
[$symbol $version]($style)\
[ ](fg:bright_green)\
"""


[conda]
ignore_base = true
style = "fg:white_smoke bg:#d2042d"
format = """
[](fg:#d2042d)\
[Env:$environment]($style)\
[ ](fg:#d2042d)\
"""

[package]
style = "fg:white_smoke bg:bright_pink"
format = """
[](fg:bright_pink)\
[$symbol$version]($style)\
[ ](fg:bright_pink)\
"""

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:sea_blue fg:white_smoke"
format = """
[](fg:sea_blue)\
[$time]($style)\
[](fg:sea_blue)\
"""
